apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: node-recaptcha
  description: Helps display and validate Recaptchas for node.js
  owner: unknown
spec:
  type: unknown
  lifecycle: production
  owner: unknown
  system: Clever
